from extra import *
import json

indian_stocks = ['RELIANCE.XNSE', 'TCS.XNSE', 'HDFCBANK.XNSE', 'HINDUNILVR.XNSE', 'HDFC.XNSE', 'ICICIBANK.XNSE', 'INFY.XNSE', 'KOTAKBANK.XNSE', 'BHARTIARTL.XNSE', 'BAJFINANCE.XNSE', 'SBIN.XNSE', 'ITC.XNSE', 'AXISBANK.XNSE', 'MARUTI.XNSE', 'ASIANPAINT.XNSE', 'LT.XNSE', 'NESTLEIND.XNSE', 'HCLTECH.XNSE', 'DMART.XNSE', 'BAJAJFINSV.XNSE', 'WIPRO.XNSE', 'ULTRACEMCO.XNSE', 'ONGC.XNSE', 'HDFCLIFE.XNSE', 'TITAN.XNSE', 'COALINDIA.XNSE', 'NTPC.XNSE', 'IOC.XNSE', 'POWERGRID.XNSE', 'BPCL.XNSE', 'SBILIFE.XNSE', 'SUNPHARMA.XNSE', 'DABUR.XNSE', 'SHREECEM.XNSE', 'BAJAJ_AUTO.XNSE', 'PIDILITIND.XNSE', 'INDUSINDBK.XNSE', 'TECHM.XNSE', 'BRITANNIA.XNSE', 'HINDZINC.XNSE', 'ADANIPORTS.XNSE', 'ICICIPRULI.XNSE', 'HDFCAMC.XNSE', 'BANDHANBNK.XNSE', 'GODREJCP.XNSE', 'M_M.XNSE', 'JSWSTEEL.XNSE', 'DIVISLAB.XNSE', 'BERGEPAINT.XNSE', 'ICICIGI.XNSE', 'DLF.XNSE', 'DRREDDY.XNSE', 'MCDOWELL_N.XNSE', 'INDIGO.XNSE', 'SIEMENS.XNSE', 'EICHERMOT.XNSE', 'TATAMOTORS.XNSE', 'GAIL.XNSE', 'GRASIM.XNSE', 'VEDL.XNSE', 'TATASTEEL.XNSE', 'AMBUJACEM.XNSE', 'INFRATEL.XNSE', 'GSKCONS.XNSE', 'HEROMOTOCO.XNSE', 'UPL.XNSE', 'HAVELLS.XNSE', 'BAJAJHLDNG.XNSE', 'MARICO.XNSE', 'BOSCHLTD.XNSE', 'PETRONET.XNSE', 'TORNTPHARM.XNSE', 'PGHH.XNSE', 'EMBASSY.RR.XNSE', 'NMDC.XNSE', 'SRTRANSFIN.XNSE', 'ADANITRANS.XNSE', 'WHIRLPOOL.XNSE', 'IRCTC.XNSE', 'KANSAINER.XNSE', 'CADILAHC.XNSE', 'TRENT.XNSE', 'GODREJPROP.XNSE', 'ACC.XNSE', 'ADANIGREEN.XNSE', 'NAM_INDIA.XNSE', 'CHOLAFIN.XNSE', 'PAGEIND.XNSE', 'ADANIENT.XNSE', 'ABB.XNSE', 'ZEEL.XNSE', 'APOLLOHOSP.XNSE', 'VBL.XNSE', 'RECLTD.XNSE', '3MINDIA.XNSE', 'SRF.XNSE', 'NHPC.XNSE', 'VOLTAS.XNSE', 'OFSS.XNSE', 'HAL.XNSE']

nasdaq_stocks = ['MSFT', 'AAPL', 'AMZN', 'GOOG', 'GOOGL', 'FB', 'VOD', 'INTC', 'CMCSA', 'PEP', 'ADBE', 'CSCO', 'NVDA', 'NFLX', 'TSLA', 'COST', 'PYPL', 'AMGN', 'SNY', 'ASML', 'AVGO', 'TXN', 'CHTR', 'SBUX', 'GILD', 'QCOM', 'TMUS', 'MDLZ', 'FISV', 'CME', 'INTU', 'BKNG', 'ADP', 'ISRG', 'VRTX', 'MU', 'AMD', 'BIIB', 'CSX', 'AMAT', 'EQIX', 'JD', 'REGN', 'ATVI', 'EXC', 'LRCX', 'NTES', 'WBA', 'ADSK', 'ILMN', 'ADI', 'ROST', 'WDAY', 'MAR', 'TEAM', 'MNST', 'XEL', 'CTSH', 'SBAC', 'NXPI', 'BIDU', 'MELI', 'EA', 'KHC', 'ZM', 'EBAY', 'TROW', 'LULU', 'CTAS', 'PAYX', 'SIRI', 'ORLY', 'VRSK', 'CSGP', 'WLTW', 'DXCM', 'KLAC', 'ERIC', 'LBRDK', 'SPLK', 'PCAR', 'LBRDA', 'PDD', 'VRSN', 'CERN', 'IDXX', 'MCHP', 'ANSS', 'SNPS', 'XP', 'ALXN', 'AMTD', 'XLNX', 'FAST', 'CPRT', 'SGEN', 'CDNS', 'MTCH', 'NDAQ', 'FOXA']

sub = ['RELIANCE.XNSE', 'TCS.XNSE', 'HDFCBANK.XNSE', 'HINDUNILVR.XNSE', 'BAJAJ_AUTO.XNSE', 'TATASTEEL.XNSE', 'INDUSINDBK.XNSE']
# sub = ['SBILIFE.XNSE', 'SUNPHARMA.XNSE', 'DABUR.XNSE', 'SHREECEM.XNSE', 'BAJAJ_AUTO.XNSE', 'PIDILITIND.XNSE', 'INDUSINDBK.XNSE']

faang = ['AAPL', 'MSFT', 'FB', 'GOOG', 'GOOGL', 'NFLX', 'AMZN','TSLA', 'TWTR','NVDA']

# new = indian_stocks + nasdaq_stocks


# data = {}
# for idx, t in enumerate(new):
#     print("Remaining tickers : ", len(new) - idx )
#     data[t] = get_ticker_data(t)
#
#
# with open('stock_data.json', 'w', encoding='utf-8') as f:
#     json.dump(data, f, ensure_ascii=False, indent=4)
